
INSERT INTO employees(rpe,name,position,speciality,email) VALUES ('9B0FMﾠAcevedo Ortega Omar EnriqueﾠJefe de oficinaProteccionesomar.acevedo@cfe.gob.mx');
INSERT INTO employees(rpe,name,position,speciality,email) VALUES ('J162R�Alvarado Garc�a Miguel�Jefe de oficinaControl de Gesti�n e inform�ticamiguel.alvarado03@cfe.gob.mx');
INSERT INTO employees(rpe,name,position,speciality,email) VALUES ('J030R�Carre�n Garc�a AaronJefe de oficinaJuridicoaaron.carreon@cfe.gob.mx');
INSERT INTO employees(rpe,name,position,speciality,email) VALUES ('9B0JK�Davila Montoya Carlos�Jefe de departamentoL�neascarlos.davila@cfe.gob.mx');
INSERT INTO employees(rpe,name,position,speciality,email) VALUES ('9B0M7�Gallegos Castro Jaime Encarnaci�n�Jefe de departamentoProteccionesjaime.gallegos@cfe.gob.mx');
INSERT INTO employees(rpe,name,position,speciality,email) VALUES ('J090R�Gonzalez Rosales GuillermoJefe de oficinaAdministraci�nguillermo.gonzalez12@cfe.gob.mxYa no est� trabajando en ZTCHIH');
INSERT INTO employees(rpe,name,position,speciality,email) VALUES ('9B0JMﾠHidalgo  Rey Oscar MarioﾠJefe de oficinaProteccionesoscar.hidalgo@cfe.gob.mx');
INSERT INTO employees(rpe,name,position,speciality,email) VALUES ('9B0TBLavin Aranda CarlosﾠJefe de oficinaComunicacionescarlos.lavin01@cfe.gob.mx');
INSERT INTO employees(rpe,name,position,speciality,email) VALUES ('9B0PWLimones Rivas Jos� Iv�nJefe de oficinaControljoseivan.limones@cfe.gob.mx');
INSERT INTO employees(rpe,name,position,speciality,email) VALUES ('CG422�Martos Iglesias Tania Belinda�Jefe de oficinaAdministraci�ntania.martos@cfe.gob.mxSe encuentran en suplencia por vacantes, no son titulares');
INSERT INTO employees(rpe,name,position,speciality,email) VALUES ('9B0GMﾠMora Dominguez Marco AntonioﾠJefe de departamentoCivilantonio.mora01@cfe.gob.mx');
INSERT INTO employees(rpe,name,position,speciality,email) VALUES ('9AB2Y�Morales P�rez Jes�s�SuperintendenteSuperintendenciajesus.morales@cfe.gob.mx');
INSERT INTO employees(rpe,name,position,speciality,email) VALUES ('CG406ﾠMota Velazco EstebanﾠJefe de oficinaComunicacionesesteban.mota@cfe.gob.mxSe encuentran en suplencia por vacantes, no son titulares');
INSERT INTO employees(rpe,name,position,speciality,email) VALUES ('9B9N1�Nevarez Guerra Mart�n Ricardo�Jefe de departamentoComunicacionesmarin.nevarez@cfe.gob.mx');
INSERT INTO employees(rpe,name,position,speciality,email) VALUES ('9B0N9�Olmos Medina Sergio Iv�n�Jefe de oficinaSubestacionessergio.olmos@cfe.gob.mx');
INSERT INTO employees(rpe,name,position,speciality,email) VALUES ('CG436ﾠOrtiz Alvarado Carlos  JaimeﾠJefe de oficinaCivilcarlos.ortiz09@cfe.gob.mxSe encuentran en suplencia por vacantes, no son titulares');
INSERT INTO employees(rpe,name,position,speciality,email) VALUES ('9A2KY�Quintana Avena Jos� CarlosJefe de departamentoControlcarlos.quintana@cfe.gob.mx');
INSERT INTO employees(rpe,name,position,speciality,email) VALUES ('9B0NBﾠRiestra caraveo ErwinﾠJefe de oficinaLineaserwin.riestra@cfe.gob.mx');
INSERT INTO employees(rpe,name,position,speciality,email) VALUES ('9B0L2ﾠRuiz de la O CastuloﾠJefe de departamentoSubestacionescastulo.ruiz@cfe.gob.mx');
INSERT INTO employees(rpe,name,position,speciality,email) VALUES ('J025R�Sanchez D�az Luis Ever�Jefe de oficinaControlluis.sanchez28@cfe.gob.mxSe encuentran en suplencia por vacantes, no son titulares');
INSERT INTO employees(rpe,name,position,speciality,email) VALUES ('9B0JL�Sol�s Cardoza V�ctor Israel�Jefe de departamentoControl de Gesti�n e inform�ticavictor.solis@cfe.gob.mx');
INSERT INTO employees(rpe,name,position,speciality,email) VALUES ('9B0RFVargas Casta�eda Julian�AdministradorAdministraci�njulian.vargas@cfe.gob.mx');
INSERT INTO employees(rpe,name,position,speciality,email) VALUES ('9B0CM�Zamarripa Madrid Mario AlbertoJefe de departamentoOperaci�n y Mantto. Sector Cuauhtemocmario.zamarripa@cfe.gob.mx');


INSERT INTO competences(name) VALUES("Obtiene Resultados");
INSERT INTO competences(name) VALUES("Adaptable");
INSERT INTO competences(name) VALUES("Ambiocioso/a");
INSERT INTO competences(name) VALUES("Accesible");
INSERT INTO competences(name) VALUES("Concilia La Vida Personal Y Laboral");
INSERT INTO competences(name) VALUES("Inteligente");
INSERT INTO competences(name) VALUES("Trabaja Bien En Equipo");
INSERT INTO competences(name) VALUES("Se Siente Cómodo/a Con La Incertidumbre");
INSERT INTO competences(name) VALUES("Se Comunica Bien (Verbalmente)");
INSERT INTO competences(name) VALUES("Se Comunica Bien (Por Escrito)");
INSERT INTO competences(name) VALUES("Calmado/a");
INSERT INTO competences(name) VALUES("Posee Confiansa En Sí Mismo/a");
INSERT INTO competences(name) VALUES("Tiene Coraje");
INSERT INTO competences(name) VALUES("Creativo/a");
INSERT INTO competences(name) VALUES("Orientado/a Al Cliente");
INSERT INTO competences(name) VALUES("Decisivo/a");
INSERT INTO competences(name) VALUES("Juicioso/a");
INSERT INTO competences(name) VALUES("Orientado/a Al Detalle");
INSERT INTO competences(name) VALUES("Perseverante");
INSERT INTO competences(name) VALUES("Desarrolla A Otras Personas");
INSERT INTO competences(name) VALUES("Se Desarrolla A Sí Mismo/a");
INSERT INTO competences(name) VALUES("Diplomático/a");
INSERT INTO competences(name) VALUES("Dirige A Las Personas");
INSERT INTO competences(name) VALUES("Empático/a");
INSERT INTO competences(name) VALUES("Sabe Delegar");
INSERT INTO competences(name) VALUES("Ético/a");
INSERT INTO competences(name) VALUES("Experimentador");
INSERT INTO competences(name) VALUES("Justo/a");
INSERT INTO competences(name) VALUES("Establece Prioridades");
INSERT INTO competences(name) VALUES("Pensador Global");
INSERT INTO competences(name) VALUES("Mejora Los Procesos");
INSERT INTO competences(name) VALUES("Informa A Otras Personas");
INSERT INTO competences(name) VALUES("Inspira Un Futuro");
INSERT INTO competences(name) VALUES("Capaz De Escuchar");
INSERT INTO competences(name) VALUES("Gestiona El Conflicto");
INSERT INTO competences(name) VALUES("Gestiona Las Ideas De Otras Personas");
INSERT INTO competences(name) VALUES("Buen Negociador/a");
INSERT INTO competences(name) VALUES("Gestiona El Bajo Rendimiento");
INSERT INTO competences(name) VALUES("Gestiona El Tiempo");
INSERT INTO competences(name) VALUES("Posee Conocimiento Del Mercado");
INSERT INTO competences(name) VALUES("Modesto/a");
INSERT INTO competences(name) VALUES("Gestiona El Trabajo");
INSERT INTO competences(name) VALUES("Motiva A Las Personas");
INSERT INTO competences(name) VALUES("Tiene Facilidad Para Establecer Relaciones");
INSERT INTO competences(name) VALUES("Comparte Información Personal");
INSERT INTO competences(name) VALUES("Abierto/a De Mente");
INSERT INTO competences(name) VALUES("Paciente");
INSERT INTO competences(name) VALUES("Planifica El Trabajo");
INSERT INTO competences(name) VALUES("Políticamente Hábil");
INSERT INTO competences(name) VALUES("Resuelve Problemas");
INSERT INTO competences(name) VALUES("Reconoce El Talento Y El Potencial En Las Personas");
INSERT INTO competences(name) VALUES("Consciente De Sí Mismo/a");
INSERT INTO competences(name) VALUES("Estratega");
INSERT INTO competences(name) VALUES("Toma Responsabilidad");
INSERT INTO competences(name) VALUES("Toma Iniciativa");
INSERT INTO competences(name) VALUES("Posee Conocimientos Técnicos");
INSERT INTO competences(name) VALUES("Experto/a En Tecnología");
INSERT INTO competences(name) VALUES("Digno/a De Confianza");
INSERT INTO competences(name) VALUES("Unifica A Las Personas");
INSERT INTO competences(name) VALUES("Tiene Una Buena Relación Con Su Jefe");